# Generated by Django 4.2 on 2023-05-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.ImageField(default=1, upload_to='department'),
            preserve_default=False,
        ),
    ]
